[package]
name = "datalilypad"
version = "0.1.0"
edition = "2021"

[dependencies]
egg = "0.10.0"
itertools = "0.14.0"
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full"] }
tap = "1.0.1"

[lib]
proc-macro = true
